# Basic Python

## 1. Split this string

In [4]:
s = "Hi there Sam!"

In [6]:
char=s
print(s.split('hi there sam'))

['Hi there Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [12]:
planet = "earth"
diameter = 12742
print('the diameter of {} is {} kilometers'.format(planet,diameter));

the diameter of earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [13]:
d ={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d["k1"][3]["tricky"][3]['target'][3]) 

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
import numpy as np
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [19]:
import numpy as np
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [24]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
x = np.concatenate((a,b))

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [26]:
import pandas as pd
data=[1,2,3]
df=pd.DataFrame(data,columns=['numbers'])
df

numbers
0        1
1        2
2        3

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [46]:
import datetime
from pandas.core.tools.datetimes import DatetimeScalarOrArrayConvertible
from datetime import date 
def numofdates(date1,date2):
    return (date2-date1),datetime
date1 = date(2023,1,1)
date2 = date(2023,2,10)
print (numofdates(date1,date2),"datetime")

(datetime.timedelta(days=40), <module 'datetime' from '/usr/lib/python3.7/datetime.py'>) datetime


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [54]:
import pandas as pd
data =[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(data,columns=['tag','number','ss'])
print (df)

   tag number  ss
0    1    aaa  22
1    2    bbb  25
2    3    ccc  24
